name: Deploy cb-backend-nest

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 161.35.37.230 >> ~/.ssh/known_hosts

    - name: Deploy Backend
      run: |
        ssh root@161.35.37.230 << 'EOF'
          cd cb-backend-nest
          git pull
          docker network create app-network || true
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          echo "✅ Backend deployment completed"
        EOF
